### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by exander77** [jalbam/nwjs_rpi#2]
nw crashes every time when started:
```
[871:0108/045032:ERROR:zygote_host_impl_linux.cc(144)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[873:0108/045034:ERROR:nss_util.cc(734)] Failed to load NSS libraries.

util.js:554
  ctor.super_ = superCtor;
              ^
TypeError: Cannot set property 'super_' of undefined
    at Object.exports.inherits (util.js:554:15)
    at Function.startup.initNw (node.js:796:34)
    at startup (node.js:67:13)
    at node.js:876:3
```

**Comment by tomasbulva** [comment]
I have the same problem. How did you resolved this problem?

**Comment by jalbam** [comment]
Hello,

Sorry about the late reply, I have been busy lately.

What hardware and operating system (and version) are you both using?

Did you follow the steps included in the README.md file?

Are you trying to run your own project or the default one that is already included (the Yasminoku game)?

If you did not try before, try to run the default project first, please. It should run well and you should see a sudoku game. After that you can try your own project (maybe adding part by part instead of adding all directly) then we could try to guess what happens with your own project that makes it crash.

Cheers,
 Joan

**Comment by tomasbulva** [comment]
Hi, I can run the sudoku game on the actual HW (pi zero, full raspbian). What I'm struggling with though is to make it run inside the docker image based on raspbian lite (I'm so far only running it as QEMU emulation). Do you have any idea what could be missing in my custom image?

**Comment by jalbam** [comment]
It seems a problem related with the QEMU to me. Since it is just an emulator, it is probably far from perfect. Or perhaps there is something wrong with that Docker image but I cannot be sure, sorry.

You are using many "layers" including emulation instead of the real hardware (which is not very powerful, specially if we are talking about the first Raspberry Pi version).

You said that in the real hardware works so I would recommend you to develop your project using NW.js for x86 (Windows, Linux or MacOS/OS X), which is the supported official version, and after that you can test it on the real hardware using the Raspberry Pi port from this repository. Personally, I would develop it step by step and test in Raspberry Pi often just to find any possible issue in time and identify easily.

I am afraid I cannot help you to identify the problem with your working environment but hopefully someone who reads this can help you.

**Comment by asial-matagawa** [comment]
@exander77 @tomasbulva @jalbam 
I had the same problem but it was fixed by just placing `nw.pak` (included in this repo) next to `Your_new_binary_file`.
Looks like `nw.pak` is always required to launch NW.js apps.
Related: https://github.com/nwjs/nw.js/issues/565#issuecomment-15365448

I hope this information could help.
